task: detection

num_classes: 80
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data0/lxj/dataset/firecoco/train/
    ann_file: /data0/lxj/dataset/firecoco/train/_annotations.coco.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 32
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /data0/lxj/dataset/firecoco/valid/
    ann_file: /data0/lxj/dataset/firecoco/valid/_annotations.coco.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 32
  num_workers: 4
  drop_last: False